name: Pack

on:
  push:
    branches:
      - main

jobs:
  pack:
    name: Pack pwned.combined.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Install dependencies
        run: |
          pip3 install -U setuptools wheel
          pip3 install -U rjsmin rcssmin

      - name: Run pack.py
        run: |
          ./pack.py

      - name: Push changes
        run: |
          if ! git diff --exit-code --quiet pwned.combined.js; then
            git commit -m "pwned: repack combined file" pwned.combined.js
            git pull --rebase
            git push
          fi
